// src/features/user-guide/constants/dummy-user-guides.ts

import type { UserGuideItem } from "@/features/user-guide/types/user-guide.type";

export const DUMMY_USER_GUIDES: UserGuideItem[] = [
  {
    id: "guide-mitra-portal-v2",
    title: "Buku Panduan Pengguna Portal Mitra IGT",
    slug: "buku-panduan-pengguna-portal-mitra-igt",
    description:
      "Panduan komprehensif alur registrasi akun mitra, permohonan data geospasial tematik, penggambaran AOI di peta, upload shapefile/GeoJSON, checkout billing SIMPONI, hingga verifikasi data.",
    category: "manual_book",
    targetRole: "mitra",
    version: "v2.1.0",
    fileName: "Manual_Book_Portal_Mitra_IGT_v2.1.pdf",
    fileUrl: "/docs/Manual_Book_Portal_Mitra_IGT_v2.1.pdf",
    fileSize: 4980736,
    fileType: "pdf",
    isPublished: true,
    downloadCount: 1240,
    author: "Tim Layanan Informasi Geospasial ATR/BPN",
    createdAt: "2026-01-15T08:00:00.000Z",
    updatedAt: "2026-09-20T14:30:00.000Z",
  },
  {
    id: "guide-api-wms-wfs",
    title: "Petunjuk Teknis Integrasi API & WMS/WFS Layer",
    slug: "petunjuk-teknis-integrasi-api-wms-wfs-layer",
    description:
      "Dokumentasi arsitektur dan panduan integrasi layanan Web Map Service (WMS) raster dan Web Feature Service (WFS) vector IGT ATR/BPN pada aplikasi SIG pihak ketiga dan sistem backend mitra.",
    category: "technical_spec",
    targetRole: "all",
    version: "v1.4.0",
    fileName: "Petunjuk_Integrasi_API_WMS_WFS_IGT_v1.4.pdf",
    fileUrl: "/docs/Petunjuk_Integrasi_API_WMS_WFS_IGT_v1.4.pdf",
    fileSize: 3450880,
    fileType: "pdf",
    isPublished: true,
    downloadCount: 875,
    author: "Direktorat Jenderal Survei & Pemetaan Pertanahan dan Ruang",
    createdAt: "2026-02-10T09:15:00.000Z",
    updatedAt: "2026-08-18T11:00:00.000Z",
  },
  {
    id: "guide-internal-admin",
    title: "Manual Book Verifikator & Administrator Internal",
    slug: "manual-book-verifikator-administrator-internal",
    description:
      "Panduan standar operasional prosedur (SOP) internal bagi tim verifikator dan admin dalam menelaah permohonan data, validasi poligon bidang/kawasan, persetujuan TTE, dan pengelolaan katalog GeoServer.",
    category: "sop",
    targetRole: "internal",
    version: "v3.0.1",
    fileName: "SOP_Admin_Verifikator_Internal_IGT_v3.0.1.pdf",
    fileUrl: "/docs/SOP_Admin_Verifikator_Internal_IGT_v3.0.1.pdf",
    fileSize: 5872025,
    fileType: "pdf",
    isPublished: true,
    downloadCount: 430,
    author: "Pusdatin Kementerian ATR/BPN",
    createdAt: "2026-01-05T07:30:00.000Z",
    updatedAt: "2026-10-01T09:45:00.000Z",
  },
  {
    id: "guide-aoi-spatial-spec",
    title: "Spesifikasi Format Data Spasial & Ketentuan AOI",
    slug: "spesifikasi-format-data-spasial-ketentuan-aoi",
    description:
      "Standar spesifikasi format data spasial area of interest (AOI), sistem referensi koordinat (EPSG:4326 WGS84), validitas topologi poligon, dan batas ukuran file unggahan pada sistem VOLATIL.",
    category: "technical_spec",
    targetRole: "all",
    version: "v1.2.0",
    fileName: "Spesifikasi_Format_Spasial_AOI_v1.2.pdf",
    fileUrl: "/docs/Spesifikasi_Format_Spasial_AOI_v1.2.pdf",
    fileSize: 2202009,
    fileType: "pdf",
    isPublished: true,
    downloadCount: 1650,
    author: "Tim Standardisasi Data Spasial ATR/BPN",
    createdAt: "2026-03-01T10:00:00.000Z",
    updatedAt: "2026-07-12T16:20:00.000Z",
  },
  {
    id: "guide-sync-jobs-geoserver",
    title: "Petunjuk Administrasi Sinkronisasi Layer & GeoServer",
    slug: "petunjuk-administrasi-sinkronisasi-layer-geoserver",
    description:
      "Panduan konfigurasi berkala untuk sinkronisasi layer data mitra, manajemen koneksi master GeoServer, cache WMS/WMTS, dan pemantauan antrean latar belakang (Sync Jobs).",
    category: "sop",
    targetRole: "internal",
    version: "v1.1.0",
    fileName: "Petunjuk_Sync_Jobs_GeoServer_v1.1.pdf",
    fileUrl: "/docs/Petunjuk_Sync_Jobs_GeoServer_v1.1.pdf",
    fileSize: 3040870,
    fileType: "pdf",
    isPublished: true,
    downloadCount: 310,
    author: "Tim Infrastruktur & Basis Data Geospasial",
    createdAt: "2026-04-14T13:00:00.000Z",
    updatedAt: "2026-09-05T10:15:00.000Z",
  },
  {
    id: "guide-help-center-faq",
    title: "Petunjuk Layanan Bantuan & Pengaduan (Help Center)",
    slug: "petunjuk-layanan-bantuan-pengaduan-help-center",
    description:
      "Petunjuk pengajuan tiket bantuan kendala teknis transaksi, eskalasi penelaahan data IGT, tata cara konsultasi perizinan tata ruang, dan FAQ seputar portal VOLATIL.",
    category: "manual_book",
    targetRole: "all",
    version: "v1.0.0",
    fileName: "Petunjuk_Layanan_Help_Center_v1.0.pdf",
    fileUrl: "/docs/Petunjuk_Layanan_Help_Center_v1.0.pdf",
    fileSize: 1572864,
    fileType: "pdf",
    isPublished: true,
    downloadCount: 920,
    author: "Biro Hubungan Masyarakat & Layanan Informasi ATR/BPN",
    createdAt: "2026-05-20T08:30:00.000Z",
    updatedAt: "2026-08-30T15:00:00.000Z",
  },
];
