// src/features/internal/data-management/types/data-management.type.ts

import type {
  PaginatedParams,
  PaginationMeta,
} from "@/shared/types/common-response.type";

export type SpatialBasisType = "bidang" | "kawasan";

export type PublishStatusType = "all" | "published" | "draft";

export type PublishStatusTypeConfig = {
  value: PublishStatusType;
  label: string;
  colorPalette: "gray" | "green";
};

export type MasterIgtLayerItem = {
  id: string;
  title: string;
  description?: string;
  spatialBasis: SpatialBasisType;
  bbox: [number, number, number, number];
  isActive: boolean;
  zIndex?: number;
  geoserverBaseUrl: string;
  typeName: string; // format: workspace:layerName
  wfsUrl: string; // readonly, generated by BE
  wmsUrl: string; // readonly, generated by BE
  createdAt: string;
  updatedAt: string;
};

export type MasterIgtLayersQueryParams = PaginatedParams & {
  spatialBasis?: SpatialBasisType;
  isActive?: boolean;
};

export type MasterIgtLayersResponse = {
  items: MasterIgtLayerItem[];
  pagination: PaginationMeta;
};

export type CreateMasterIgtLayerPayload = {
  id: string;
  title: string;
  description?: string;
  spatialBasis: SpatialBasisType;
  bbox: [number, number, number, number];
  isActive: boolean;
  zIndex?: number;
  geoserverBaseUrl: string;
  typeName: string;
  wfsUrl: string;
  wmsUrl: string;
};

export type UpdateMasterIgtLayerPayload =
  Partial<CreateMasterIgtLayerPayload> & {
    id: string;
  };
