// src/shared/constants/dummy-data.ts

import type { CatalogItemDataResponse } from "@/features/data-request/types/data-request.catalog.type";
import type { HomeDataResponse } from "@/features/home/types/home.data-summary.type";

export const homeData: HomeDataResponse = {
  dataSummary: {
    "1d": {
      field: { active: 100, almostExpired: 20, expired: 5 },
      area: { active: 50, almostExpired: 10, expired: 3 },
    },
    "1w": {
      field: { active: 800, almostExpired: 150, expired: 40 },
      area: { active: 400, almostExpired: 80, expired: 20 },
    },
    "1m": {
      field: { active: 3000, almostExpired: 500, expired: 150 },
      area: { active: 1500, almostExpired: 300, expired: 80 },
    },
    "1y": {
      field: { active: 8000, almostExpired: 2500, expired: 1200 },
      area: { active: 5500, almostExpired: 1800, expired: 800 },
    },
    all: {
      field: { active: 12000, almostExpired: 4000, expired: 2000 },
      area: { active: 8500, almostExpired: 3000, expired: 1500 },
    },
  },
  financialFlow: {
    "1d": [
      { sale: 1500000, label: "00:00" },
      { sale: 3200000, label: "06:00" },
      { sale: 8750000, label: "12:00" },
      { sale: 4100000, label: "18:00" },
    ],
    "1w": [
      { sale: 12500000, label: "Senin" },
      { sale: 18300000, label: "Selasa" },
      { sale: 21000000, label: "Rabu" },
      { sale: 9800000, label: "Kamis" },
      { sale: 25600000, label: "Jumat" },
      { sale: 7200000, label: "Sabtu" },
      { sale: 4500000, label: "Minggu" },
    ],
    "1m": [
      { sale: 87500000, label: "W1" },
      { sale: 112000000, label: "W2" },
      { sale: 134500000, label: "W3" },
      { sale: 98700000, label: "W4" },
    ],
    "1y": [
      { sale: 312000000, label: "Jan" },
      { sale: 289000000, label: "Feb" },
      { sale: 401000000, label: "Mar" },
      { sale: 378000000, label: "Apr" },
      { sale: 456000000, label: "Mei" },
      { sale: 521000000, label: "Jun" },
      { sale: 498000000, label: "Jul" },
      { sale: 612000000, label: "Agu" },
      { sale: 589000000, label: "Sep" },
      { sale: 634000000, label: "Okt" },
      { sale: 701000000, label: "Nov" },
      { sale: 689000000, label: "Des" },
    ],
    all: [
      { sale: 890000000, label: "2021" },
      { sale: 1120000000, label: "2022" },
      { sale: 1380000000, label: "2023" },
      { sale: 1650000000, label: "2024" },
      { sale: 1920000000, label: "2025" },
      { sale: 2200000000, label: "2026" },
    ],
  },
  cartSummary: {
    totalField: 150,
    totalArea: 45,
    totalIgtData: 195,
    subtotalPrice: 15000000,
  },
  lastTransactions: [
    {
      id: "1",
      transactionNo: "XYZ-580-00-756",
      username: "adminvolatil.atrbpn",
      date: "Senin, 24 Januari 2027",
      status: "success",
      dataName: "AGT - 01",
      themeType: "rtr",
      apiLink: "https://wps.atrbpn.go...",
      apiWps: "geospatial/wps/run...",
      timeLeft: "55h : 22j : 59m",
      dataStatus: "active",
      quota: "1000/1000",
      themeCategory: "spatial",
      description:
        "Data ini merupakan data IGT-PR hasil olahan Rencana Tata Ruang Kabupaten Semarang dengan skala 1:10.000",
      amount: 4500000,
    },
    {
      id: "2",
      transactionNo: "XYZ-580-00-756",
      username: "adminvolatil.atrbpn",
      date: "Senin, 24 Januari 2027",
      status: "success",
      dataName: "AGT - 02",
      themeType: "boundary",
      apiLink: "https://wps.atrbpn.go...",
      apiWps: "geospatial/wps/run...",
      timeLeft: "55h : 22j : 59m",
      dataStatus: "active",
      quota: "1000/1000",
      themeCategory: "land",
      description:
        "Data ini merupakan data IGT-PR hasil olahan Rencana Tata Ruang Kabupaten Semarang dengan skala 1:10.000",
      amount: 2500000,
    },
    {
      id: "3",
      transactionNo: "XYZ-580-00-756",
      username: "adminvolatil.atrbpn",
      date: "Senin, 24 Januari 2027",
      status: "success",
      dataName: "AGT - 03",
      themeType: "land",
      apiLink: "https://wps.atrbpn.go...",
      apiWps: "geospatial/wps/run...",
      timeLeft: "55h : 22j : 59m",
      dataStatus: "active",
      quota: "1000/1000",
      themeCategory: "spatial",
      description:
        "Data ini merupakan data IGT-PR hasil olahan Rencana Tata Ruang Kabupaten Semarang dengan skala 1:10.000",
      amount: 4500000,
    },
    {
      id: "4",
      transactionNo: "XYZ-580-00-756",
      username: "adminvolatil.atrbpn",
      date: "Senin, 24 Januari 2027",
      status: "success",
      dataName: "AGT - 04",
      themeType: "boundary",
      apiLink: "https://wps.atrbpn.go...",
      apiWps: "geospatial/wps/run...",
      timeLeft: "0h : 0j : 0m",
      dataStatus: "inactive",
      quota: "1000/1000",
      themeCategory: "land",
      description:
        "Data ini merupakan data IGT-PR hasil olahan Rencana Tata Ruang Kabupaten Semarang dengan skala 1:10.000",
      amount: 2500000,
    },
    {
      id: "5",
      transactionNo: "XYZ-580-00-756",
      username: "adminvolatil.atrbpn",
      date: "Senin, 24 Januari 2027",
      status: "success",
      dataName: "AGT - 05",
      themeType: "rtr",
      apiLink: "https://wps.atrbpn.go...",
      apiWps: "geospatial/wps/run...",
      timeLeft: "0h : 0j : 0m",
      dataStatus: "inactive",
      quota: "1000/1000",
      themeCategory: "spatial",
      description:
        "Data ini merupakan data IGT-PR hasil olahan Rencana Tata Ruang Kabupaten Semarang dengan skala 1:10.000",
      amount: 1500000,
    },
  ],
};

export const catalogData: CatalogItemDataResponse[] = [
  {
    id: "1",
    name: "AOI - 01",
    themeType: "bidang",
    quotaBase: 1000,
    categories: ["hak_atas_tanah", "pemilikan_tanah", "bidang_tanah"],
    description:
      "Data ini terdiri dari 8 tema IGT-PR berbasis bidang dengan total 1000 bidang dan luas kawasan 1000 ha²",
    price: 7500000,
  },
  {
    id: "2",
    name: "AOI - 02",
    themeType: "kawasan",
    quotaBase: 1000,
    categories: ["rtrw_nasional", "rtrw_provinsi", "rtrw_kota"],
    description:
      "Data ini terdiri dari 8 tema IGT-PR berbasis kawasan dengan total 1000 bidang dan luas kawasan 1000 ha²",
    price: 20000000,
  },
  {
    id: "3",
    name: "AOI - 03",
    themeType: "bidang",
    quotaBase: 1000,
    categories: ["hak_atas_tanah", "pemilikan_tanah", "bidang_tanah"],
    description:
      "Data ini terdiri dari 8 tema IGT-PR berbasis bidang dengan total 1000 bidang dan luas kawasan 1000 ha²",
    price: 7500000,
  },
  {
    id: "4",
    name: "AOI - 04",
    themeType: "kawasan",
    quotaBase: 1000,
    categories: ["rtrw_nasional", "rtrw_provinsi", "rtrw_kota"],
    description:
      "Data ini terdiri dari 8 tema IGT-PR berbasis kawasan dengan total 1000 bidang dan luas kawasan 1000 ha²",
    price: 20000000,
  },
  {
    id: "5",
    name: "AOI - 05",
    themeType: "bidang",
    quotaBase: 1000,
    categories: ["hak_atas_tanah", "pemilikan_tanah", "bidang_tanah"],
    description:
      "Data ini terdiri dari 8 tema IGT-PR berbasis bidang dengan total 1000 bidang dan luas kawasan 1000 ha²",
    price: 3750000,
  },
  {
    id: "6",
    name: "AOI - 06",
    themeType: "kawasan",
    quotaBase: 1000,
    categories: ["rtrw_nasional", "rtrw_provinsi", "rtrw_kota"],
    description:
      "Data ini terdiri dari 8 tema IGT-PR berbasis kawasan dengan total 1000 bidang dan luas kawasan 1000 ha²",
    price: 20000000,
  },
  {
    id: "7",
    name: "AOI - 07",
    themeType: "bidang",
    quotaBase: 1000,
    categories: ["hak_atas_tanah", "pemilikan_tanah", "bidang_tanah"],
    description:
      "Data ini terdiri dari 8 tema IGT-PR berbasis bidang dengan total 1000 bidang dan luas kawasan 1000 ha²",
    price: 7500000,
  },
  {
    id: "8",
    name: "AOI - 08",
    themeType: "kawasan",
    quotaBase: 1000,
    categories: ["rtrw_nasional", "rtrw_provinsi", "rtrw_kota"],
    description:
      "Data ini terdiri dari 8 tema IGT-PR berbasis kawasan dengan total 1000 bidang dan luas kawasan 1000 ha²",
    price: 20000000,
  },
  {
    id: "9",
    name: "AOI - 09",
    themeType: "bidang",
    quotaBase: 1000,
    categories: ["hak_atas_tanah", "pemilikan_tanah", "bidang_tanah"],
    description:
      "Data ini terdiri dari 8 tema IGT-PR berbasis bidang dengan total 1000 bidang dan luas kawasan 1000 ha²",
    price: 7500000,
  },
  {
    id: "10",
    name: "AOI - 10",
    themeType: "kawasan",
    quotaBase: 1000,
    categories: ["rtrw_nasional", "rtrw_provinsi", "rtrw_kota"],
    description:
      "Data ini terdiri dari 8 tema IGT-PR berbasis kawasan dengan total 1000 bidang dan luas kawasan 1000 ha²",
    price: 20000000,
  },
  {
    id: "11",
    name: "AOI - 11",
    themeType: "bidang",
    quotaBase: 1000,
    categories: ["hak_atas_tanah", "pemilikan_tanah", "bidang_tanah"],
    description:
      "Data ini terdiri dari 8 tema IGT-PR berbasis bidang dengan total 1000 bidang dan luas kawasan 1000 ha²",
    price: 7500000,
  },
  {
    id: "12",
    name: "AOI - 12",
    themeType: "kawasan",
    quotaBase: 1000,
    categories: ["rtrw_nasional", "rtrw_provinsi", "rtrw_kota"],
    description:
      "Data ini terdiri dari 8 tema IGT-PR berbasis kawasan dengan total 1000 bidang dan luas kawasan 1000 ha²",
    price: 20000000,
  },
  {
    id: "13",
    name: "AOI - 13",
    themeType: "bidang",
    quotaBase: 1000,
    categories: ["hak_atas_tanah", "pemilikan_tanah", "bidang_tanah"],
    description:
      "Data ini terdiri dari 8 tema IGT-PR berbasis bidang dengan total 1000 bidang dan luas kawasan 1000 ha²",
    price: 7500000,
  },
  {
    id: "14",
    name: "AOI - 14",
    themeType: "kawasan",
    quotaBase: 1000,
    categories: ["rtrw_nasional", "rtrw_provinsi", "rtrw_kota"],
    description:
      "Data ini terdiri dari 8 tema IGT-PR berbasis kawasan dengan total 1000 bidang dan luas kawasan 1000 ha²",
    price: 20000000,
  },
  {
    id: "15",
    name: "AOI - 15",
    themeType: "bidang",
    quotaBase: 1000,
    categories: ["hak_atas_tanah", "pemilikan_tanah", "bidang_tanah"],
    description:
      "Data ini terdiri dari 8 tema IGT-PR berbasis bidang dengan total 1000 bidang dan luas kawasan 1000 ha²",
    price: 3750000,
  },
  {
    id: "16",
    name: "AOI - 16",
    themeType: "kawasan",
    quotaBase: 1000,
    categories: ["rtrw_nasional", "rtrw_provinsi", "rtrw_kota"],
    description:
      "Data ini terdiri dari 8 tema IGT-PR berbasis kawasan dengan total 1000 bidang dan luas kawasan 1000 ha²",
    price: 20000000,
  },
  {
    id: "17",
    name: "AOI - 17",
    themeType: "bidang",
    quotaBase: 1000,
    categories: ["hak_atas_tanah", "pemilikan_tanah", "bidang_tanah"],
    description:
      "Data ini terdiri dari 8 tema IGT-PR berbasis bidang dengan total 1000 bidang dan luas kawasan 1000 ha²",
    price: 7500000,
  },
  {
    id: "18",
    name: "AOI - 18",
    themeType: "kawasan",
    quotaBase: 1000,
    categories: ["rtrw_nasional", "rtrw_provinsi", "rtrw_kota"],
    description:
      "Data ini terdiri dari 8 tema IGT-PR berbasis kawasan dengan total 1000 bidang dan luas kawasan 1000 ha²",
    price: 20000000,
  },
  {
    id: "19",
    name: "AOI - 19",
    themeType: "bidang",
    quotaBase: 1000,
    categories: ["hak_atas_tanah", "pemilikan_tanah", "bidang_tanah"],
    description:
      "Data ini terdiri dari 8 tema IGT-PR berbasis bidang dengan total 1000 bidang dan luas kawasan 1000 ha²",
    price: 7500000,
  },
  {
    id: "20",
    name: "AOI - 20",
    themeType: "kawasan",
    quotaBase: 1000,
    categories: ["rtrw_nasional", "rtrw_provinsi", "rtrw_kota"],
    description:
      "Data ini terdiri dari 8 tema IGT-PR berbasis kawasan dengan total 1000 bidang dan luas kawasan 1000 ha²",
    price: 20000000,
  },
];
