// src/shared/constants/dummy-data.ts

import type { HomeDataResponse } from "@/features/home/types/home.data-summary.type";

export const homeData: HomeDataResponse = {
  dataSummary: {
    field: {
      active: 12000,
      almostExpired: 4000,
      expired: 2000,
    },
    area: {
      active: 8500,
      almostExpired: 3000,
      expired: 1500,
    },
  },
  cartSummary: {
    totalField: 150,
    totalArea: 45,
    totalIgtData: 195,
    subtotalPrice: 15000000,
  },
  lastTransactions: [
    {
      id: "1",
      transactionNo: "XYZ-580-00-756",
      username: "adminvolatil.atrbpn",
      date: "Senin, 24 Januari 2027",
      status: "success",
      dataName: "AGT - 01",
      themeType: "rtr",
      apiLink: "https://wps.atrbpn.go...",
      apiWps: "geospatial/wps/run...",
      timeLeft: "55h : 22j : 59m",
      dataStatus: "active",
      quota: "1000/1000",
      themeCategory: "spatial",
      description: "Data ini merupakan data IGT-PR hasil olahan Rencana Tata Ruang Kabupaten Semarang dengan skala 1:10.000",
      amount: 4500000,
    },
    {
      id: "2",
      transactionNo: "XYZ-580-00-756",
      username: "adminvolatil.atrbpn",
      date: "Senin, 24 Januari 2027",
      status: "success",
      dataName: "AGT - 02",
      themeType: "boundary",
      apiLink: "https://wps.atrbpn.go...",
      apiWps: "geospatial/wps/run...",
      timeLeft: "55h : 22j : 59m",
      dataStatus: "active",
      quota: "1000/1000",
      themeCategory: "land",
      description: "Data ini merupakan data IGT-PR hasil olahan Rencana Tata Ruang Kabupaten Semarang dengan skala 1:10.000",
      amount: 2500000,
    },
    {
      id: "3",
      transactionNo: "XYZ-580-00-756",
      username: "adminvolatil.atrbpn",
      date: "Senin, 24 Januari 2027",
      status: "success",
      dataName: "AGT - 03",
      themeType: "land",
      apiLink: "https://wps.atrbpn.go...",
      apiWps: "geospatial/wps/run...",
      timeLeft: "55h : 22j : 59m",
      dataStatus: "active",
      quota: "1000/1000",
      themeCategory: "spatial",
      description: "Data ini merupakan data IGT-PR hasil olahan Rencana Tata Ruang Kabupaten Semarang dengan skala 1:10.000",
      amount: 4500000,
    },
    {
      id: "4",
      transactionNo: "XYZ-580-00-756",
      username: "adminvolatil.atrbpn",
      date: "Senin, 24 Januari 2027",
      status: "success",
      dataName: "AGT - 04",
      themeType: "boundary",
      apiLink: "https://wps.atrbpn.go...",
      apiWps: "geospatial/wps/run...",
      timeLeft: "0h : 0j : 0m",
      dataStatus: "inactive",
      quota: "1000/1000",
      themeCategory: "land",
      description: "Data ini merupakan data IGT-PR hasil olahan Rencana Tata Ruang Kabupaten Semarang dengan skala 1:10.000",
      amount: 2500000,
    },
    {
      id: "5",
      transactionNo: "XYZ-580-00-756",
      username: "adminvolatil.atrbpn",
      date: "Senin, 24 Januari 2027",
      status: "success",
      dataName: "AGT - 05",
      themeType: "rtr",
      apiLink: "https://wps.atrbpn.go...",
      apiWps: "geospatial/wps/run...",
      timeLeft: "0h : 0j : 0m",
      dataStatus: "inactive",
      quota: "1000/1000",
      themeCategory: "spatial",
      description: "Data ini merupakan data IGT-PR hasil olahan Rencana Tata Ruang Kabupaten Semarang dengan skala 1:10.000",
      amount: 1500000,
    },
  ],
};
