// src/shared/constants/status.config.ts
// Re-export SSOT maps from orders.config.ts

export {
  MY_DATA_ORDER_STATUS_OPTIONS,
  MY_DATA_STATUS_MAP,
  MY_DATA_STATUS_OPTIONS,
  ORDER_STATUS_MAP,
  PAYMENT_METHOD_LABEL_MAP,
  SELECTION_TYPE_CONFIG_MAP,
  IGT_BASIS_MAP,
  IGT_BASIS_OPTIONS,
  SPATIAL_BASIS_CONFIG_MAP,
  SPATIAL_BASIS_OPTIONS,
  TRANSACTION_STATUS_MAP,
  TRANSACTION_STATUS_OPTIONS,
} from "@/features/shared/constants/volatil.ssot-map";
