// src/shared/constants/dummy-data/dummy-internal-order-review.ts

import type { InternalOrderItem } from "@/features/internal/order-review/types/order-review.type";

const now = new Date();

export const DUMMY_INTERNAL_ORDERS: InternalOrderItem[] = [
  {
    orderId: "ord-2026-0830-001",
    orderNumber: "ORD-20260830-001",
    transactionNumber: "TRX-20260830-001",
    workspaceName: "ws_ord_20260830_001",
    internalWorkspaceUrl:
      "https://geoserver.internal.volatil.atrbpn.go.id/geoserver/ws_ord_20260830_001/ows",
    workspaceInteropUrl:
      "https://geoportal.atrbpn.go.id/interop/wms?workspace=ws_ord_20260830_001",
    mitraId: "mtr-001",
    mitraName: "PT Graha Pembangunan Persada",
    agencyOrCompany: "PT Graha Pembangunan Persada",
    email: "contact@grahapembangunan.co.id",
    status: "paid",
    selectionType: "draw_aoi",
    createdAt: new Date(now.getTime() - 1000 * 60 * 45).toISOString(),
    totalPrice: 1850000,
    invoiceUrl:
      "https://volatil-be.exium.web.id/invoices/INV-ord-2026-0830-001.pdf",
    tteInvoiceUrl: null,
    tte: false,
    coverageHa: 145.85,
    items: [
      {
        id: "coi-001",
        sourceLayerId: "testing_workspace:TEST_BIDANG_TANAH",
        sourceLayerTitle: "Bidang Tanah Kadastral Badung",
        spatialBasis: "bidang",
        featuresCount: 24,
        unitPrice: 50000,
        subtotalPrice: 1200000,
        wfsUrl: "/api/proxy/wfs?layerId=testing_workspace:TEST_BIDANG_TANAH",
        wmsUrl: "/api/proxy/wms?layerId=testing_workspace:TEST_BIDANG_TANAH",
        previewWfsUrl:
          "/api/proxy/wfs?layerId=testing_workspace:TEST_BIDANG_TANAH",
        previewWmsUrl:
          "/api/proxy/wms?layerId=testing_workspace:TEST_BIDANG_TANAH",
      },
      {
        id: "coi-002",
        sourceLayerId: "testing_workspace:TEST_RTRW_BADUNG",
        sourceLayerTitle: "RTRW Pola Ruang Kab. Badung",
        spatialBasis: "kawasan",
        featuresCount: 2,
        areaHa: 13.5,
        unitPrice: 50000,
        subtotalPrice: 650000,
        wfsUrl: "/api/proxy/wfs?layerId=testing_workspace:TEST_RTRW_BADUNG",
        wmsUrl: "/api/proxy/wms?layerId=testing_workspace:TEST_RTRW_BADUNG",
        previewWfsUrl:
          "/api/proxy/wfs?layerId=testing_workspace:TEST_RTRW_BADUNG",
        previewWmsUrl:
          "/api/proxy/wms?layerId=testing_workspace:TEST_RTRW_BADUNG",
      },
      {
        id: "coi-003",
        sourceLayerId: "testing_workspace:TEST_ZNT_BADUNG",
        sourceLayerTitle: "Zona Nilai Tanah (ZNT) Badung",
        spatialBasis: "bidang",
        featuresCount: 18,
        unitPrice: 50000,
        subtotalPrice: 900000,
        previewWfsUrl:
          "/api/proxy/wfs?layerId=testing_workspace:TEST_ZNT_BADUNG",
        previewWmsUrl:
          "/api/proxy/wms?layerId=testing_workspace:TEST_ZNT_BADUNG",
      },
      {
        id: "coi-004",
        sourceLayerId: "testing_workspace:TEST_HUTAN_LINDUNG",
        sourceLayerTitle: "Kawasan Hutan Lindung",
        spatialBasis: "kawasan",
        featuresCount: 1,
        areaHa: 45.2,
        unitPrice: 50000,
        subtotalPrice: 500000,
      },
      {
        id: "coi-005",
        sourceLayerId: "testing_workspace:TEST_HUTAN_PRODUKSI",
        sourceLayerTitle: "Kawasan Hutan Produksi Terbatas",
        spatialBasis: "kawasan",
        featuresCount: 3,
        areaHa: 62.1,
        unitPrice: 50000,
        subtotalPrice: 500000,
      },
      {
        id: "coi-006",
        sourceLayerId: "testing_workspace:TEST_HAK_GUNA_BANGUNAN",
        sourceLayerTitle: "Hak Guna Bangunan (HGB)",
        spatialBasis: "bidang",
        featuresCount: 12,
        unitPrice: 50000,
        subtotalPrice: 600000,
      },
      {
        id: "coi-007",
        sourceLayerId: "testing_workspace:TEST_HAK_MILIK",
        sourceLayerTitle: "Hak Milik Perorangan",
        spatialBasis: "bidang",
        featuresCount: 45,
        unitPrice: 50000,
        subtotalPrice: 2250000,
      },
      {
        id: "coi-008",
        sourceLayerId: "testing_workspace:TEST_HAK_PAKAI",
        sourceLayerTitle: "Hak Pakai Instansi Pemerintah",
        spatialBasis: "bidang",
        featuresCount: 4,
        unitPrice: 50000,
        subtotalPrice: 200000,
      },
      {
        id: "coi-009",
        sourceLayerId: "testing_workspace:TEST_RDTR_ZONASI",
        sourceLayerTitle: "RDTR Zonasi Perdagangan & Jasa",
        spatialBasis: "kawasan",
        featuresCount: 5,
        areaHa: 18.3,
        unitPrice: 50000,
        subtotalPrice: 500000,
      },
      {
        id: "coi-010",
        sourceLayerId: "testing_workspace:TEST_RDTR_PERUMAHAN",
        sourceLayerTitle: "RDTR Zonasi Perumahan Kepadatan Tinggi",
        spatialBasis: "kawasan",
        featuresCount: 8,
        areaHa: 25.4,
        unitPrice: 50000,
        subtotalPrice: 500000,
      },
      {
        id: "coi-011",
        sourceLayerId: "testing_workspace:TEST_SEMPADAN_PANTAI",
        sourceLayerTitle: "Kawasan Sempadan Pantai",
        spatialBasis: "kawasan",
        featuresCount: 2,
        areaHa: 8.7,
        unitPrice: 50000,
        subtotalPrice: 500000,
      },
      {
        id: "coi-012",
        sourceLayerId: "testing_workspace:TEST_SEMPADAN_SUNGAI",
        sourceLayerTitle: "Kawasan Sempadan Sungai",
        spatialBasis: "kawasan",
        featuresCount: 4,
        areaHa: 12.0,
        unitPrice: 50000,
        subtotalPrice: 500000,
      },
      {
        id: "coi-013",
        sourceLayerId: "testing_workspace:TEST_LP2B",
        sourceLayerTitle: "Lahan Pertanian Pangan Berkelanjutan (LP2B)",
        spatialBasis: "kawasan",
        featuresCount: 6,
        areaHa: 34.2,
        unitPrice: 50000,
        subtotalPrice: 500000,
      },
      {
        id: "coi-014",
        sourceLayerId: "testing_workspace:TEST_RAWAN_LONGSOR",
        sourceLayerTitle: "Kawasan Rawan Bencana Gerakan Tanah / Longsor",
        spatialBasis: "kawasan",
        featuresCount: 1,
        areaHa: 15.0,
        unitPrice: 50000,
        subtotalPrice: 500000,
      },
      {
        id: "coi-015",
        sourceLayerId: "testing_workspace:TEST_RAWAN_BANJIR",
        sourceLayerTitle: "Kawasan Rawan Banjir Genangan",
        spatialBasis: "kawasan",
        featuresCount: 2,
        areaHa: 22.5,
        unitPrice: 50000,
        subtotalPrice: 500000,
      },
      {
        id: "coi-016",
        sourceLayerId: "testing_workspace:TEST_CAGAR_BUDAYA",
        sourceLayerTitle: "Situs & Kawasan Cagar Budaya",
        spatialBasis: "kawasan",
        featuresCount: 2,
        areaHa: 4.1,
        unitPrice: 50000,
        subtotalPrice: 500000,
      },
      {
        id: "coi-017",
        sourceLayerId: "testing_workspace:TEST_HAK_GUNA_USAHA",
        sourceLayerTitle: "Hak Guna Usaha (HGU) Perkebunan",
        spatialBasis: "bidang",
        featuresCount: 3,
        unitPrice: 50000,
        subtotalPrice: 150000,
      },
      {
        id: "coi-018",
        sourceLayerId: "testing_workspace:TEST_HAK_PENGELOLAAN",
        sourceLayerTitle: "Hak Pengelolaan (HPL) Pemda",
        spatialBasis: "bidang",
        featuresCount: 2,
        unitPrice: 50000,
        subtotalPrice: 100000,
      },
      {
        id: "coi-019",
        sourceLayerId: "testing_workspace:TEST_TANAH_KAS_DESA",
        sourceLayerTitle: "Tanah Kas Desa / Kelurahan",
        spatialBasis: "bidang",
        featuresCount: 7,
        unitPrice: 50000,
        subtotalPrice: 350000,
      },
      {
        id: "coi-020",
        sourceLayerId: "testing_workspace:TEST_TANAH_WAKAF",
        sourceLayerTitle: "Tanah Wakaf Terdaftar",
        spatialBasis: "bidang",
        featuresCount: 5,
        unitPrice: 50000,
        subtotalPrice: 250000,
      },
      {
        id: "coi-021",
        sourceLayerId: "testing_workspace:TEST_KKOP",
        sourceLayerTitle: "Kawasan Keselamatan Operasi Penerbangan (KKOP)",
        spatialBasis: "kawasan",
        featuresCount: 1,
        areaHa: 80.0,
        unitPrice: 50000,
        subtotalPrice: 500000,
      },
      {
        id: "coi-022",
        sourceLayerId: "testing_workspace:TEST_INDUSTRI",
        sourceLayerTitle: "Kawasan Peruntukan Industri (KPI)",
        spatialBasis: "kawasan",
        featuresCount: 3,
        areaHa: 40.0,
        unitPrice: 50000,
        subtotalPrice: 500000,
      },
      {
        id: "coi-023",
        sourceLayerId: "testing_workspace:TEST_PARIWISATA",
        sourceLayerTitle: "Kawasan Strategis Pariwisata Daerah",
        spatialBasis: "kawasan",
        featuresCount: 4,
        areaHa: 30.5,
        unitPrice: 50000,
        subtotalPrice: 500000,
      },
      {
        id: "coi-024",
        sourceLayerId: "testing_workspace:TEST_MANGROVE",
        sourceLayerTitle: "Ekosistem Mangrove Lindung",
        spatialBasis: "kawasan",
        featuresCount: 2,
        areaHa: 11.2,
        unitPrice: 50000,
        subtotalPrice: 500000,
      },
      {
        id: "coi-025",
        sourceLayerId: "testing_workspace:TEST_TERUMBU_KARANG",
        sourceLayerTitle: "Kawasan Konservasi Terumbu Karang",
        spatialBasis: "kawasan",
        featuresCount: 1,
        areaHa: 16.8,
        unitPrice: 50000,
        subtotalPrice: 500000,
      },
      {
        id: "coi-026",
        sourceLayerId: "testing_workspace:TEST_RESAPAN_AIR",
        sourceLayerTitle: "Kawasan Resapan Air Utama",
        spatialBasis: "kawasan",
        featuresCount: 2,
        areaHa: 55.0,
        unitPrice: 50000,
        subtotalPrice: 500000,
      },
      {
        id: "coi-027",
        sourceLayerId: "testing_workspace:TEST_BATAS_ADMIN_DESA",
        sourceLayerTitle: "Batas Administrasi Desa / Kelurahan",
        spatialBasis: "kawasan",
        featuresCount: 8,
        areaHa: 120.0,
        unitPrice: 50000,
        subtotalPrice: 500000,
      },
      {
        id: "coi-028",
        sourceLayerId: "testing_workspace:TEST_BATAS_KECAMATAN",
        sourceLayerTitle: "Batas Administrasi Kecamatan",
        spatialBasis: "kawasan",
        featuresCount: 3,
        areaHa: 145.85,
        unitPrice: 50000,
        subtotalPrice: 500000,
      },
      {
        id: "coi-029",
        sourceLayerId: "testing_workspace:TEST_KANTOR_PERTANAHAN",
        sourceLayerTitle: "Sebaran Kantor Pertanahan & Layanan",
        spatialBasis: "bidang",
        featuresCount: 2,
        unitPrice: 50000,
        subtotalPrice: 100000,
      },
      {
        id: "coi-030",
        sourceLayerId: "testing_workspace:TEST_TITIK_DASAR_TEKNIK",
        sourceLayerTitle: "Titik Dasar Teknik Orde 3 & 4",
        spatialBasis: "bidang",
        featuresCount: 38,
        unitPrice: 50000,
        subtotalPrice: 1900000,
      },
      {
        id: "coi-031",
        sourceLayerId: "testing_workspace:TEST_JALUR_PIPA_GAS",
        sourceLayerTitle: "Koridor Jalur Pipa Gas & Energi",
        spatialBasis: "kawasan",
        featuresCount: 1,
        areaHa: 5.5,
        unitPrice: 50000,
        subtotalPrice: 500000,
      },
      {
        id: "coi-032",
        sourceLayerId: "testing_workspace:TEST_SUTT_SUTET",
        sourceLayerTitle: "Koridor Jalur SUTT / SUTET Listrik",
        spatialBasis: "kawasan",
        featuresCount: 2,
        areaHa: 9.3,
        unitPrice: 50000,
        subtotalPrice: 500000,
      },
      {
        id: "coi-033",
        sourceLayerId: "testing_workspace:TEST_JALAN_TOL",
        sourceLayerTitle: "Ruang Milik Jalan (Rumija) Tol",
        spatialBasis: "kawasan",
        featuresCount: 3,
        areaHa: 14.8,
        unitPrice: 50000,
        subtotalPrice: 500000,
      },
      {
        id: "coi-034",
        sourceLayerId: "testing_workspace:TEST_REL_KERETA",
        sourceLayerTitle: "Ruang Pengawasan Jalur Kereta Api",
        spatialBasis: "kawasan",
        featuresCount: 1,
        areaHa: 7.2,
        unitPrice: 50000,
        subtotalPrice: 500000,
      },
      {
        id: "coi-035",
        sourceLayerId: "testing_workspace:TEST_PELABUHAN",
        sourceLayerTitle: "Daerah Lingkungan Kerja Pelabuhan (DLKr)",
        spatialBasis: "kawasan",
        featuresCount: 1,
        areaHa: 28.0,
        unitPrice: 50000,
        subtotalPrice: 500000,
      },
      {
        id: "coi-036",
        sourceLayerId: "testing_workspace:TEST_BANDARA",
        sourceLayerTitle: "Daerah Lingkungan Kerja Bandara (DLKr Bandara)",
        spatialBasis: "kawasan",
        featuresCount: 1,
        areaHa: 65.0,
        unitPrice: 50000,
        subtotalPrice: 500000,
      },
      {
        id: "coi-037",
        sourceLayerId: "testing_workspace:TEST_KONSESI_TAMBANG",
        sourceLayerTitle: "Wilayah Izin Usaha Pertambangan (WIUP)",
        spatialBasis: "kawasan",
        featuresCount: 2,
        areaHa: 48.0,
        unitPrice: 50000,
        subtotalPrice: 500000,
      },
      {
        id: "coi-038",
        sourceLayerId: "testing_workspace:TEST_REKLAMASI",
        sourceLayerTitle: "Kawasan Rencana Reklamasi Pantai",
        spatialBasis: "kawasan",
        featuresCount: 1,
        areaHa: 12.4,
        unitPrice: 50000,
        subtotalPrice: 500000,
      },
      {
        id: "coi-039",
        sourceLayerId: "testing_workspace:TEST_GEOPARK",
        sourceLayerTitle: "Situs Warisan Geologi (Geopark)",
        spatialBasis: "kawasan",
        featuresCount: 1,
        areaHa: 32.0,
        unitPrice: 50000,
        subtotalPrice: 500000,
      },
    ],
  },
  {
    orderId: "ord-2026-0830-002",
    orderNumber: "ORD-20260830-002",
    transactionNumber: "TRX-20260830-002",
    workspaceName: "ws_ord_20260830_002",
    internalWorkspaceUrl:
      "https://geoserver.internal.volatil.atrbpn.go.id/geoserver/ws_ord_20260830_002/ows",
    workspaceInteropUrl: null,
    mitraId: "mtr-002",
    mitraName: "PT Nusantara Infrastruktur Utama",
    agencyOrCompany: "PT Nusantara Infrastruktur Utama",
    email: "info@nusantarainfra.id",
    status: "pending_review",
    selectionType: "upload_aoi",
    createdAt: new Date(now.getTime() - 1000 * 60 * 120).toISOString(),
    totalPrice: 950000,
    invoiceUrl:
      "https://volatil-be.exium.web.id/invoices/INV-ord-2026-0830-002.pdf",
    tteInvoiceUrl: null,
    tte: false,
    items: [
      {
        id: "coi-003",
        sourceLayerId: "testing_workspace:TEST_ZNT_BADUNG",
        sourceLayerTitle: "Zona Nilai Tanah (ZNT) Badung",
        spatialBasis: "bidang",
        featuresCount: 19,
        unitPrice: 50000,
        subtotalPrice: 950000,
        wfsUrl: "/api/proxy/wfs?layerId=testing_workspace:TEST_ZNT_BADUNG",
        wmsUrl: "/api/proxy/wms?layerId=testing_workspace:TEST_ZNT_BADUNG",
        previewWfsUrl:
          "/api/proxy/wfs?layerId=testing_workspace:TEST_ZNT_BADUNG",
        previewWmsUrl:
          "/api/proxy/wms?layerId=testing_workspace:TEST_ZNT_BADUNG",
      },
    ],
  },
  {
    orderId: "ord-2026-0829-003",
    orderNumber: "ORD-20260829-003",
    transactionNumber: "TRX-20260829-003",
    workspaceName: "ws_ord_20260829_003",
    internalWorkspaceUrl:
      "https://geoserver.internal.volatil.atrbpn.go.id/geoserver/ws_ord_20260829_003/ows",
    workspaceInteropUrl:
      "https://geoportal.atrbpn.go.id/interop/wms?workspace=ws_ord_20260829_003",
    mitraId: "mtr-003",
    mitraName: "CV Agraria Citra Mandiri",
    agencyOrCompany: "CV Agraria Citra Mandiri",
    email: "admin@agrariacitra.com",
    status: "ready",
    selectionType: "draw_aoi",
    createdAt: new Date(now.getTime() - 1000 * 60 * 60 * 5).toISOString(),
    readyAt: new Date(now.getTime() - 1000 * 60 * 60 * 4).toISOString(),
    expiredAt: new Date(now.getTime() + 1000 * 60 * 60 * 20).toISOString(),
    totalPrice: 500000,
    invoiceUrl:
      "https://volatil-be.exium.web.id/invoices/INV-ord-2026-0829-003.pdf",
    tteInvoiceUrl:
      "https://volatil-be.exium.web.id/invoices/TTE-INV-ord-2026-0829-003.pdf",
    tte: true,
    items: [
      {
        id: "coi-004",
        sourceLayerId: "testing_workspace:TEST_RTRW_BADUNG",
        sourceLayerTitle: "RTRW Kabupaten Badung",
        spatialBasis: "kawasan",
        featuresCount: 1,
        areaHa: 10,
        unitPrice: 50000,
        subtotalPrice: 500000,
        previewWfsUrl:
          "/api/proxy/wfs?layerId=testing_workspace:TEST_RTRW_BADUNG",
        previewWmsUrl:
          "/api/proxy/wms?layerId=testing_workspace:TEST_RTRW_BADUNG",
      },
    ],
  },
  {
    orderId: "ord-2026-0828-004",
    orderNumber: "ORD-20260828-004",
    transactionNumber: "TRX-20260828-004",
    workspaceName: "ws_ord_20260828_004",
    internalWorkspaceUrl:
      "https://geoserver.internal.volatil.atrbpn.go.id/geoserver/ws_ord_20260828_004/ows",
    workspaceInteropUrl: null,
    mitraId: "mtr-001",
    mitraName: "PT Graha Pembangunan Persada",
    agencyOrCompany: "PT Graha Pembangunan Persada",
    email: "contact@grahapembangunan.co.id",
    status: "rejected",
    selectionType: "catalog",
    createdAt: new Date(now.getTime() - 1000 * 60 * 60 * 24).toISOString(),
    totalPrice: 750000,
    invoiceUrl: null,
    tteInvoiceUrl: null,
    tte: false,
    items: [
      {
        id: "coi-005",
        sourceLayerId: "testing_workspace:TEST_BIDANG_TANAH",
        sourceLayerTitle: "Bidang Tanah Kadastral Badung",
        spatialBasis: "bidang",
        featuresCount: 15,
        unitPrice: 50000,
        subtotalPrice: 750000,
        previewWfsUrl:
          "/api/proxy/wfs?layerId=testing_workspace:TEST_BIDANG_TANAH",
        previewWmsUrl:
          "/api/proxy/wms?layerId=testing_workspace:TEST_BIDANG_TANAH",
      },
    ],
  },
];
