// src/shared/constants/dummy-data/dummy-my-data.ts

import type { MyDataItem } from "@/features/mitra/my-data/types/my-data.type";

export const dummyMitraMyDataItems: MyDataItem[] = [
  {
    id: "testing_workspace:TEST_RTRW_BADUNG",
    title: "RTRW Badung",
    spatialBasis: "kawasan",
    wfsUrl: "https://igtpr.atrbpn.go.id/geoserver/testing_workspace/ows?service=WFS&request=GetCapabilities",
    wmsUrl: "https://igtpr.atrbpn.go.id/geoserver/testing_workspace/wms?service=WMS&request=GetCapabilities",
    wfsTypeName: "testing_workspace:TEST_RTRW_BADUNG",
    wmsLayers: "testing_workspace:TEST_RTRW_BADUNG",
    status: "active",
    expiresAt: "2026-12-31T23:59:59.000Z",
    bbox: [115.083839, -8.850039, 115.251389, -8.239441],
  },
  {
    id: "testing_workspace:TEST_ZNT_BADUNG",
    title: "ZNT Badung",
    spatialBasis: "kawasan",
    wfsUrl: "https://igtpr.atrbpn.go.id/geoserver/testing_workspace/ows?service=WFS&request=GetCapabilities",
    wmsUrl: "https://igtpr.atrbpn.go.id/geoserver/testing_workspace/wms?service=WMS&request=GetCapabilities",
    wfsTypeName: "testing_workspace:TEST_ZNT_BADUNG",
    wmsLayers: "testing_workspace:TEST_ZNT_BADUNG",
    status: "active",
    expiresAt: "2026-11-30T23:59:59.000Z",
    bbox: [115.083839, -8.849308, 115.251534, -8.239852],
  },
  {
    id: "testing_workspace:TEST_BIDANG_TANAH",
    title: "Bidang Tanah",
    spatialBasis: "bidang",
    wfsUrl: "https://igtpr.atrbpn.go.id/geoserver/testing_workspace/ows?service=WFS&request=GetCapabilities",
    wmsUrl: "https://igtpr.atrbpn.go.id/geoserver/testing_workspace/wms?service=WMS&request=GetCapabilities",
    wfsTypeName: "testing_workspace:TEST_BIDANG_TANAH",
    wmsLayers: "testing_workspace:TEST_BIDANG_TANAH",
    status: "active",
    expiresAt: "2026-10-15T12:00:00.000Z",
    bbox: [115.134102, -8.685009, 115.183136, -8.622203],
  },
  {
    id: "testing_workspace:TEST_BIDANG_DENPASAR",
    title: "Bidang Tanah Denpasar Timur",
    spatialBasis: "bidang",
    wfsUrl: "/api/proxy/wfs?layerId=testing_workspace:TEST_BIDANG_DENPASAR",
    wmsUrl: "/api/proxy/wms?layerId=testing_workspace:TEST_BIDANG_DENPASAR",
    status: "processing",
    expiresAt: "2026-10-03T10:25:00.000Z",
    bbox: [115.2, -8.65, 115.25, -8.6],
  },
  {
    id: "testing_workspace:TEST_KAWASAN_SANUR",
    title: "Kawasan Pesisir Sanur",
    spatialBasis: "kawasan",
    wfsUrl: "/api/proxy/wfs?layerId=testing_workspace:TEST_KAWASAN_SANUR",
    wmsUrl: "/api/proxy/wms?layerId=testing_workspace:TEST_KAWASAN_SANUR",
    status: "pending_verification",
    expiresAt: "2026-10-03T10:25:00.000Z",
    bbox: [115.24, -8.7, 115.28, -8.66],
  },
  {
    id: "testing_workspace:TEST_RDTR_KUTA",
    title: "RDTR Kuta",
    spatialBasis: "kawasan",
    wfsUrl: "https://igtpr.atrbpn.go.id/geoserver/testing_workspace/ows?service=WFS&request=GetCapabilities",
    wmsUrl: "https://igtpr.atrbpn.go.id/geoserver/testing_workspace/wms?service=WMS&request=GetCapabilities",
    wfsTypeName: "testing_workspace:TEST_RDTR_KUTA",
    wmsLayers: "testing_workspace:TEST_RDTR_KUTA",
    status: "expired",
    expiresAt: "2026-01-01T00:00:00.000Z",
    bbox: [115.15, -8.75, 115.2, -8.68],
  },
];
