/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DemoRouteImport } from './routes/demo'
import { Route as PrivateRouteRouteImport } from './routes/_private/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PublicRegistrationStatusRouteImport } from './routes/_public/registration-status'
import { Route as PublicRegisterRouteImport } from './routes/_public/register'
import { Route as PublicAdminRouteImport } from './routes/_public/admin'
import { Route as PrivateMitraWelcomeRouteImport } from './routes/_private/mitra/welcome'
import { Route as PrivateMitraTransactionHistoryRouteImport } from './routes/_private/mitra/transaction-history'
import { Route as PrivateMitraNotificationRouteImport } from './routes/_private/mitra/notification'
import { Route as PrivateMitraMyDataRouteImport } from './routes/_private/mitra/my-data'
import { Route as PrivateMitraHomeRouteImport } from './routes/_private/mitra/home'
import { Route as PrivateMitraDataRequestRouteImport } from './routes/_private/mitra/data-request'
import { Route as PrivateMitraCartRouteImport } from './routes/_private/mitra/cart'
import { Route as PrivateInternalWelcomeRouteImport } from './routes/_private/internal/welcome'
import { Route as PrivateInternalUserManagementRouteImport } from './routes/_private/internal/user-management'
import { Route as PrivateInternalOrderStatisticRouteImport } from './routes/_private/internal/order-statistic'
import { Route as PrivateInternalOrderReviewRouteImport } from './routes/_private/internal/order-review'
import { Route as PrivateInternalNotificationRouteImport } from './routes/_private/internal/notification'
import { Route as PrivateInternalMitraRegistrationRouteImport } from './routes/_private/internal/mitra-registration'
import { Route as PrivateInternalMasterGeoserverRouteImport } from './routes/_private/internal/master-geoserver'
import { Route as PrivateInternalHomeRouteImport } from './routes/_private/internal/home'
import { Route as PrivateInternalHelpCenterRouteImport } from './routes/_private/internal/help-center'
import { Route as PrivateInternalDataManagementRouteImport } from './routes/_private/internal/data-management'
import { Route as PrivateMitraHelpCenterIndexRouteImport } from './routes/_private/mitra/help-center.index'
import { Route as PrivateInternalOrderReviewIndexRouteImport } from './routes/_private/internal/order-review.index'
import { Route as PrivateInternalMitraRegistrationIndexRouteImport } from './routes/_private/internal/mitra-registration.index'
import { Route as PrivateMitraHelpCenterTicketIdRouteImport } from './routes/_private/mitra/help-center.$ticketId'
import { Route as PrivateMitraBillingBillingCodeRouteImport } from './routes/_private/mitra/billing.$billingCode'
import { Route as PrivateInternalOrderReviewOrderIdRouteImport } from './routes/_private/internal/order-review.$orderId'
import { Route as PrivateInternalMitraRegistrationRegistrationIdRouteImport } from './routes/_private/internal/mitra-registration.$registrationId'
import { Route as PrivateInternalOrderReviewOrderIdIndexRouteImport } from './routes/_private/internal/order-review.$orderId.index'
import { Route as PrivateInternalOrderReviewOrderIdLayerLayerIdRouteImport } from './routes/_private/internal/order-review.$orderId.layer.$layerId'

const DemoRoute = DemoRouteImport.update({
  id: '/demo',
  path: '/demo',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivateRouteRoute = PrivateRouteRouteImport.update({
  id: '/_private',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicRegistrationStatusRoute =
  PublicRegistrationStatusRouteImport.update({
    id: '/_public/registration-status',
    path: '/registration-status',
    getParentRoute: () => rootRouteImport,
  } as any)
const PublicRegisterRoute = PublicRegisterRouteImport.update({
  id: '/_public/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicAdminRoute = PublicAdminRouteImport.update({
  id: '/_public/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivateMitraWelcomeRoute = PrivateMitraWelcomeRouteImport.update({
  id: '/mitra/welcome',
  path: '/mitra/welcome',
  getParentRoute: () => PrivateRouteRoute,
} as any)
const PrivateMitraTransactionHistoryRoute =
  PrivateMitraTransactionHistoryRouteImport.update({
    id: '/mitra/transaction-history',
    path: '/mitra/transaction-history',
    getParentRoute: () => PrivateRouteRoute,
  } as any)
const PrivateMitraNotificationRoute =
  PrivateMitraNotificationRouteImport.update({
    id: '/mitra/notification',
    path: '/mitra/notification',
    getParentRoute: () => PrivateRouteRoute,
  } as any)
const PrivateMitraMyDataRoute = PrivateMitraMyDataRouteImport.update({
  id: '/mitra/my-data',
  path: '/mitra/my-data',
  getParentRoute: () => PrivateRouteRoute,
} as any)
const PrivateMitraHomeRoute = PrivateMitraHomeRouteImport.update({
  id: '/mitra/home',
  path: '/mitra/home',
  getParentRoute: () => PrivateRouteRoute,
} as any)
const PrivateMitraDataRequestRoute = PrivateMitraDataRequestRouteImport.update({
  id: '/mitra/data-request',
  path: '/mitra/data-request',
  getParentRoute: () => PrivateRouteRoute,
} as any)
const PrivateMitraCartRoute = PrivateMitraCartRouteImport.update({
  id: '/mitra/cart',
  path: '/mitra/cart',
  getParentRoute: () => PrivateRouteRoute,
} as any)
const PrivateInternalWelcomeRoute = PrivateInternalWelcomeRouteImport.update({
  id: '/internal/welcome',
  path: '/internal/welcome',
  getParentRoute: () => PrivateRouteRoute,
} as any)
const PrivateInternalUserManagementRoute =
  PrivateInternalUserManagementRouteImport.update({
    id: '/internal/user-management',
    path: '/internal/user-management',
    getParentRoute: () => PrivateRouteRoute,
  } as any)
const PrivateInternalOrderStatisticRoute =
  PrivateInternalOrderStatisticRouteImport.update({
    id: '/internal/order-statistic',
    path: '/internal/order-statistic',
    getParentRoute: () => PrivateRouteRoute,
  } as any)
const PrivateInternalOrderReviewRoute =
  PrivateInternalOrderReviewRouteImport.update({
    id: '/internal/order-review',
    path: '/internal/order-review',
    getParentRoute: () => PrivateRouteRoute,
  } as any)
const PrivateInternalNotificationRoute =
  PrivateInternalNotificationRouteImport.update({
    id: '/internal/notification',
    path: '/internal/notification',
    getParentRoute: () => PrivateRouteRoute,
  } as any)
const PrivateInternalMitraRegistrationRoute =
  PrivateInternalMitraRegistrationRouteImport.update({
    id: '/internal/mitra-registration',
    path: '/internal/mitra-registration',
    getParentRoute: () => PrivateRouteRoute,
  } as any)
const PrivateInternalMasterGeoserverRoute =
  PrivateInternalMasterGeoserverRouteImport.update({
    id: '/internal/master-geoserver',
    path: '/internal/master-geoserver',
    getParentRoute: () => PrivateRouteRoute,
  } as any)
const PrivateInternalHomeRoute = PrivateInternalHomeRouteImport.update({
  id: '/internal/home',
  path: '/internal/home',
  getParentRoute: () => PrivateRouteRoute,
} as any)
const PrivateInternalHelpCenterRoute =
  PrivateInternalHelpCenterRouteImport.update({
    id: '/internal/help-center',
    path: '/internal/help-center',
    getParentRoute: () => PrivateRouteRoute,
  } as any)
const PrivateInternalDataManagementRoute =
  PrivateInternalDataManagementRouteImport.update({
    id: '/internal/data-management',
    path: '/internal/data-management',
    getParentRoute: () => PrivateRouteRoute,
  } as any)
const PrivateMitraHelpCenterIndexRoute =
  PrivateMitraHelpCenterIndexRouteImport.update({
    id: '/mitra/help-center/',
    path: '/mitra/help-center/',
    getParentRoute: () => PrivateRouteRoute,
  } as any)
const PrivateInternalOrderReviewIndexRoute =
  PrivateInternalOrderReviewIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => PrivateInternalOrderReviewRoute,
  } as any)
const PrivateInternalMitraRegistrationIndexRoute =
  PrivateInternalMitraRegistrationIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => PrivateInternalMitraRegistrationRoute,
  } as any)
const PrivateMitraHelpCenterTicketIdRoute =
  PrivateMitraHelpCenterTicketIdRouteImport.update({
    id: '/mitra/help-center/$ticketId',
    path: '/mitra/help-center/$ticketId',
    getParentRoute: () => PrivateRouteRoute,
  } as any)
const PrivateMitraBillingBillingCodeRoute =
  PrivateMitraBillingBillingCodeRouteImport.update({
    id: '/mitra/billing/$billingCode',
    path: '/mitra/billing/$billingCode',
    getParentRoute: () => PrivateRouteRoute,
  } as any)
const PrivateInternalOrderReviewOrderIdRoute =
  PrivateInternalOrderReviewOrderIdRouteImport.update({
    id: '/$orderId',
    path: '/$orderId',
    getParentRoute: () => PrivateInternalOrderReviewRoute,
  } as any)
const PrivateInternalMitraRegistrationRegistrationIdRoute =
  PrivateInternalMitraRegistrationRegistrationIdRouteImport.update({
    id: '/$registrationId',
    path: '/$registrationId',
    getParentRoute: () => PrivateInternalMitraRegistrationRoute,
  } as any)
const PrivateInternalOrderReviewOrderIdIndexRoute =
  PrivateInternalOrderReviewOrderIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => PrivateInternalOrderReviewOrderIdRoute,
  } as any)
const PrivateInternalOrderReviewOrderIdLayerLayerIdRoute =
  PrivateInternalOrderReviewOrderIdLayerLayerIdRouteImport.update({
    id: '/layer/$layerId',
    path: '/layer/$layerId',
    getParentRoute: () => PrivateInternalOrderReviewOrderIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/demo': typeof DemoRoute
  '/admin': typeof PublicAdminRoute
  '/register': typeof PublicRegisterRoute
  '/registration-status': typeof PublicRegistrationStatusRoute
  '/internal/data-management': typeof PrivateInternalDataManagementRoute
  '/internal/help-center': typeof PrivateInternalHelpCenterRoute
  '/internal/home': typeof PrivateInternalHomeRoute
  '/internal/master-geoserver': typeof PrivateInternalMasterGeoserverRoute
  '/internal/mitra-registration': typeof PrivateInternalMitraRegistrationRouteWithChildren
  '/internal/notification': typeof PrivateInternalNotificationRoute
  '/internal/order-review': typeof PrivateInternalOrderReviewRouteWithChildren
  '/internal/order-statistic': typeof PrivateInternalOrderStatisticRoute
  '/internal/user-management': typeof PrivateInternalUserManagementRoute
  '/internal/welcome': typeof PrivateInternalWelcomeRoute
  '/mitra/cart': typeof PrivateMitraCartRoute
  '/mitra/data-request': typeof PrivateMitraDataRequestRoute
  '/mitra/home': typeof PrivateMitraHomeRoute
  '/mitra/my-data': typeof PrivateMitraMyDataRoute
  '/mitra/notification': typeof PrivateMitraNotificationRoute
  '/mitra/transaction-history': typeof PrivateMitraTransactionHistoryRoute
  '/mitra/welcome': typeof PrivateMitraWelcomeRoute
  '/internal/mitra-registration/$registrationId': typeof PrivateInternalMitraRegistrationRegistrationIdRoute
  '/internal/order-review/$orderId': typeof PrivateInternalOrderReviewOrderIdRouteWithChildren
  '/mitra/billing/$billingCode': typeof PrivateMitraBillingBillingCodeRoute
  '/mitra/help-center/$ticketId': typeof PrivateMitraHelpCenterTicketIdRoute
  '/internal/mitra-registration/': typeof PrivateInternalMitraRegistrationIndexRoute
  '/internal/order-review/': typeof PrivateInternalOrderReviewIndexRoute
  '/mitra/help-center/': typeof PrivateMitraHelpCenterIndexRoute
  '/internal/order-review/$orderId/': typeof PrivateInternalOrderReviewOrderIdIndexRoute
  '/internal/order-review/$orderId/layer/$layerId': typeof PrivateInternalOrderReviewOrderIdLayerLayerIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/demo': typeof DemoRoute
  '/admin': typeof PublicAdminRoute
  '/register': typeof PublicRegisterRoute
  '/registration-status': typeof PublicRegistrationStatusRoute
  '/internal/data-management': typeof PrivateInternalDataManagementRoute
  '/internal/help-center': typeof PrivateInternalHelpCenterRoute
  '/internal/home': typeof PrivateInternalHomeRoute
  '/internal/master-geoserver': typeof PrivateInternalMasterGeoserverRoute
  '/internal/notification': typeof PrivateInternalNotificationRoute
  '/internal/order-statistic': typeof PrivateInternalOrderStatisticRoute
  '/internal/user-management': typeof PrivateInternalUserManagementRoute
  '/internal/welcome': typeof PrivateInternalWelcomeRoute
  '/mitra/cart': typeof PrivateMitraCartRoute
  '/mitra/data-request': typeof PrivateMitraDataRequestRoute
  '/mitra/home': typeof PrivateMitraHomeRoute
  '/mitra/my-data': typeof PrivateMitraMyDataRoute
  '/mitra/notification': typeof PrivateMitraNotificationRoute
  '/mitra/transaction-history': typeof PrivateMitraTransactionHistoryRoute
  '/mitra/welcome': typeof PrivateMitraWelcomeRoute
  '/internal/mitra-registration/$registrationId': typeof PrivateInternalMitraRegistrationRegistrationIdRoute
  '/mitra/billing/$billingCode': typeof PrivateMitraBillingBillingCodeRoute
  '/mitra/help-center/$ticketId': typeof PrivateMitraHelpCenterTicketIdRoute
  '/internal/mitra-registration': typeof PrivateInternalMitraRegistrationIndexRoute
  '/internal/order-review': typeof PrivateInternalOrderReviewIndexRoute
  '/mitra/help-center': typeof PrivateMitraHelpCenterIndexRoute
  '/internal/order-review/$orderId': typeof PrivateInternalOrderReviewOrderIdIndexRoute
  '/internal/order-review/$orderId/layer/$layerId': typeof PrivateInternalOrderReviewOrderIdLayerLayerIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_private': typeof PrivateRouteRouteWithChildren
  '/demo': typeof DemoRoute
  '/_public/admin': typeof PublicAdminRoute
  '/_public/register': typeof PublicRegisterRoute
  '/_public/registration-status': typeof PublicRegistrationStatusRoute
  '/_private/internal/data-management': typeof PrivateInternalDataManagementRoute
  '/_private/internal/help-center': typeof PrivateInternalHelpCenterRoute
  '/_private/internal/home': typeof PrivateInternalHomeRoute
  '/_private/internal/master-geoserver': typeof PrivateInternalMasterGeoserverRoute
  '/_private/internal/mitra-registration': typeof PrivateInternalMitraRegistrationRouteWithChildren
  '/_private/internal/notification': typeof PrivateInternalNotificationRoute
  '/_private/internal/order-review': typeof PrivateInternalOrderReviewRouteWithChildren
  '/_private/internal/order-statistic': typeof PrivateInternalOrderStatisticRoute
  '/_private/internal/user-management': typeof PrivateInternalUserManagementRoute
  '/_private/internal/welcome': typeof PrivateInternalWelcomeRoute
  '/_private/mitra/cart': typeof PrivateMitraCartRoute
  '/_private/mitra/data-request': typeof PrivateMitraDataRequestRoute
  '/_private/mitra/home': typeof PrivateMitraHomeRoute
  '/_private/mitra/my-data': typeof PrivateMitraMyDataRoute
  '/_private/mitra/notification': typeof PrivateMitraNotificationRoute
  '/_private/mitra/transaction-history': typeof PrivateMitraTransactionHistoryRoute
  '/_private/mitra/welcome': typeof PrivateMitraWelcomeRoute
  '/_private/internal/mitra-registration/$registrationId': typeof PrivateInternalMitraRegistrationRegistrationIdRoute
  '/_private/internal/order-review/$orderId': typeof PrivateInternalOrderReviewOrderIdRouteWithChildren
  '/_private/mitra/billing/$billingCode': typeof PrivateMitraBillingBillingCodeRoute
  '/_private/mitra/help-center/$ticketId': typeof PrivateMitraHelpCenterTicketIdRoute
  '/_private/internal/mitra-registration/': typeof PrivateInternalMitraRegistrationIndexRoute
  '/_private/internal/order-review/': typeof PrivateInternalOrderReviewIndexRoute
  '/_private/mitra/help-center/': typeof PrivateMitraHelpCenterIndexRoute
  '/_private/internal/order-review/$orderId/': typeof PrivateInternalOrderReviewOrderIdIndexRoute
  '/_private/internal/order-review/$orderId/layer/$layerId': typeof PrivateInternalOrderReviewOrderIdLayerLayerIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/demo'
    | '/admin'
    | '/register'
    | '/registration-status'
    | '/internal/data-management'
    | '/internal/help-center'
    | '/internal/home'
    | '/internal/master-geoserver'
    | '/internal/mitra-registration'
    | '/internal/notification'
    | '/internal/order-review'
    | '/internal/order-statistic'
    | '/internal/user-management'
    | '/internal/welcome'
    | '/mitra/cart'
    | '/mitra/data-request'
    | '/mitra/home'
    | '/mitra/my-data'
    | '/mitra/notification'
    | '/mitra/transaction-history'
    | '/mitra/welcome'
    | '/internal/mitra-registration/$registrationId'
    | '/internal/order-review/$orderId'
    | '/mitra/billing/$billingCode'
    | '/mitra/help-center/$ticketId'
    | '/internal/mitra-registration/'
    | '/internal/order-review/'
    | '/mitra/help-center/'
    | '/internal/order-review/$orderId/'
    | '/internal/order-review/$orderId/layer/$layerId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/demo'
    | '/admin'
    | '/register'
    | '/registration-status'
    | '/internal/data-management'
    | '/internal/help-center'
    | '/internal/home'
    | '/internal/master-geoserver'
    | '/internal/notification'
    | '/internal/order-statistic'
    | '/internal/user-management'
    | '/internal/welcome'
    | '/mitra/cart'
    | '/mitra/data-request'
    | '/mitra/home'
    | '/mitra/my-data'
    | '/mitra/notification'
    | '/mitra/transaction-history'
    | '/mitra/welcome'
    | '/internal/mitra-registration/$registrationId'
    | '/mitra/billing/$billingCode'
    | '/mitra/help-center/$ticketId'
    | '/internal/mitra-registration'
    | '/internal/order-review'
    | '/mitra/help-center'
    | '/internal/order-review/$orderId'
    | '/internal/order-review/$orderId/layer/$layerId'
  id:
    | '__root__'
    | '/'
    | '/_private'
    | '/demo'
    | '/_public/admin'
    | '/_public/register'
    | '/_public/registration-status'
    | '/_private/internal/data-management'
    | '/_private/internal/help-center'
    | '/_private/internal/home'
    | '/_private/internal/master-geoserver'
    | '/_private/internal/mitra-registration'
    | '/_private/internal/notification'
    | '/_private/internal/order-review'
    | '/_private/internal/order-statistic'
    | '/_private/internal/user-management'
    | '/_private/internal/welcome'
    | '/_private/mitra/cart'
    | '/_private/mitra/data-request'
    | '/_private/mitra/home'
    | '/_private/mitra/my-data'
    | '/_private/mitra/notification'
    | '/_private/mitra/transaction-history'
    | '/_private/mitra/welcome'
    | '/_private/internal/mitra-registration/$registrationId'
    | '/_private/internal/order-review/$orderId'
    | '/_private/mitra/billing/$billingCode'
    | '/_private/mitra/help-center/$ticketId'
    | '/_private/internal/mitra-registration/'
    | '/_private/internal/order-review/'
    | '/_private/mitra/help-center/'
    | '/_private/internal/order-review/$orderId/'
    | '/_private/internal/order-review/$orderId/layer/$layerId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PrivateRouteRoute: typeof PrivateRouteRouteWithChildren
  DemoRoute: typeof DemoRoute
  PublicAdminRoute: typeof PublicAdminRoute
  PublicRegisterRoute: typeof PublicRegisterRoute
  PublicRegistrationStatusRoute: typeof PublicRegistrationStatusRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/demo': {
      id: '/demo'
      path: '/demo'
      fullPath: '/demo'
      preLoaderRoute: typeof DemoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_private': {
      id: '/_private'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PrivateRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public/registration-status': {
      id: '/_public/registration-status'
      path: '/registration-status'
      fullPath: '/registration-status'
      preLoaderRoute: typeof PublicRegistrationStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public/register': {
      id: '/_public/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof PublicRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public/admin': {
      id: '/_public/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof PublicAdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_private/mitra/welcome': {
      id: '/_private/mitra/welcome'
      path: '/mitra/welcome'
      fullPath: '/mitra/welcome'
      preLoaderRoute: typeof PrivateMitraWelcomeRouteImport
      parentRoute: typeof PrivateRouteRoute
    }
    '/_private/mitra/transaction-history': {
      id: '/_private/mitra/transaction-history'
      path: '/mitra/transaction-history'
      fullPath: '/mitra/transaction-history'
      preLoaderRoute: typeof PrivateMitraTransactionHistoryRouteImport
      parentRoute: typeof PrivateRouteRoute
    }
    '/_private/mitra/notification': {
      id: '/_private/mitra/notification'
      path: '/mitra/notification'
      fullPath: '/mitra/notification'
      preLoaderRoute: typeof PrivateMitraNotificationRouteImport
      parentRoute: typeof PrivateRouteRoute
    }
    '/_private/mitra/my-data': {
      id: '/_private/mitra/my-data'
      path: '/mitra/my-data'
      fullPath: '/mitra/my-data'
      preLoaderRoute: typeof PrivateMitraMyDataRouteImport
      parentRoute: typeof PrivateRouteRoute
    }
    '/_private/mitra/home': {
      id: '/_private/mitra/home'
      path: '/mitra/home'
      fullPath: '/mitra/home'
      preLoaderRoute: typeof PrivateMitraHomeRouteImport
      parentRoute: typeof PrivateRouteRoute
    }
    '/_private/mitra/data-request': {
      id: '/_private/mitra/data-request'
      path: '/mitra/data-request'
      fullPath: '/mitra/data-request'
      preLoaderRoute: typeof PrivateMitraDataRequestRouteImport
      parentRoute: typeof PrivateRouteRoute
    }
    '/_private/mitra/cart': {
      id: '/_private/mitra/cart'
      path: '/mitra/cart'
      fullPath: '/mitra/cart'
      preLoaderRoute: typeof PrivateMitraCartRouteImport
      parentRoute: typeof PrivateRouteRoute
    }
    '/_private/internal/welcome': {
      id: '/_private/internal/welcome'
      path: '/internal/welcome'
      fullPath: '/internal/welcome'
      preLoaderRoute: typeof PrivateInternalWelcomeRouteImport
      parentRoute: typeof PrivateRouteRoute
    }
    '/_private/internal/user-management': {
      id: '/_private/internal/user-management'
      path: '/internal/user-management'
      fullPath: '/internal/user-management'
      preLoaderRoute: typeof PrivateInternalUserManagementRouteImport
      parentRoute: typeof PrivateRouteRoute
    }
    '/_private/internal/order-statistic': {
      id: '/_private/internal/order-statistic'
      path: '/internal/order-statistic'
      fullPath: '/internal/order-statistic'
      preLoaderRoute: typeof PrivateInternalOrderStatisticRouteImport
      parentRoute: typeof PrivateRouteRoute
    }
    '/_private/internal/order-review': {
      id: '/_private/internal/order-review'
      path: '/internal/order-review'
      fullPath: '/internal/order-review'
      preLoaderRoute: typeof PrivateInternalOrderReviewRouteImport
      parentRoute: typeof PrivateRouteRoute
    }
    '/_private/internal/notification': {
      id: '/_private/internal/notification'
      path: '/internal/notification'
      fullPath: '/internal/notification'
      preLoaderRoute: typeof PrivateInternalNotificationRouteImport
      parentRoute: typeof PrivateRouteRoute
    }
    '/_private/internal/mitra-registration': {
      id: '/_private/internal/mitra-registration'
      path: '/internal/mitra-registration'
      fullPath: '/internal/mitra-registration'
      preLoaderRoute: typeof PrivateInternalMitraRegistrationRouteImport
      parentRoute: typeof PrivateRouteRoute
    }
    '/_private/internal/master-geoserver': {
      id: '/_private/internal/master-geoserver'
      path: '/internal/master-geoserver'
      fullPath: '/internal/master-geoserver'
      preLoaderRoute: typeof PrivateInternalMasterGeoserverRouteImport
      parentRoute: typeof PrivateRouteRoute
    }
    '/_private/internal/home': {
      id: '/_private/internal/home'
      path: '/internal/home'
      fullPath: '/internal/home'
      preLoaderRoute: typeof PrivateInternalHomeRouteImport
      parentRoute: typeof PrivateRouteRoute
    }
    '/_private/internal/help-center': {
      id: '/_private/internal/help-center'
      path: '/internal/help-center'
      fullPath: '/internal/help-center'
      preLoaderRoute: typeof PrivateInternalHelpCenterRouteImport
      parentRoute: typeof PrivateRouteRoute
    }
    '/_private/internal/data-management': {
      id: '/_private/internal/data-management'
      path: '/internal/data-management'
      fullPath: '/internal/data-management'
      preLoaderRoute: typeof PrivateInternalDataManagementRouteImport
      parentRoute: typeof PrivateRouteRoute
    }
    '/_private/mitra/help-center/': {
      id: '/_private/mitra/help-center/'
      path: '/mitra/help-center'
      fullPath: '/mitra/help-center/'
      preLoaderRoute: typeof PrivateMitraHelpCenterIndexRouteImport
      parentRoute: typeof PrivateRouteRoute
    }
    '/_private/internal/order-review/': {
      id: '/_private/internal/order-review/'
      path: '/'
      fullPath: '/internal/order-review/'
      preLoaderRoute: typeof PrivateInternalOrderReviewIndexRouteImport
      parentRoute: typeof PrivateInternalOrderReviewRoute
    }
    '/_private/internal/mitra-registration/': {
      id: '/_private/internal/mitra-registration/'
      path: '/'
      fullPath: '/internal/mitra-registration/'
      preLoaderRoute: typeof PrivateInternalMitraRegistrationIndexRouteImport
      parentRoute: typeof PrivateInternalMitraRegistrationRoute
    }
    '/_private/mitra/help-center/$ticketId': {
      id: '/_private/mitra/help-center/$ticketId'
      path: '/mitra/help-center/$ticketId'
      fullPath: '/mitra/help-center/$ticketId'
      preLoaderRoute: typeof PrivateMitraHelpCenterTicketIdRouteImport
      parentRoute: typeof PrivateRouteRoute
    }
    '/_private/mitra/billing/$billingCode': {
      id: '/_private/mitra/billing/$billingCode'
      path: '/mitra/billing/$billingCode'
      fullPath: '/mitra/billing/$billingCode'
      preLoaderRoute: typeof PrivateMitraBillingBillingCodeRouteImport
      parentRoute: typeof PrivateRouteRoute
    }
    '/_private/internal/order-review/$orderId': {
      id: '/_private/internal/order-review/$orderId'
      path: '/$orderId'
      fullPath: '/internal/order-review/$orderId'
      preLoaderRoute: typeof PrivateInternalOrderReviewOrderIdRouteImport
      parentRoute: typeof PrivateInternalOrderReviewRoute
    }
    '/_private/internal/mitra-registration/$registrationId': {
      id: '/_private/internal/mitra-registration/$registrationId'
      path: '/$registrationId'
      fullPath: '/internal/mitra-registration/$registrationId'
      preLoaderRoute: typeof PrivateInternalMitraRegistrationRegistrationIdRouteImport
      parentRoute: typeof PrivateInternalMitraRegistrationRoute
    }
    '/_private/internal/order-review/$orderId/': {
      id: '/_private/internal/order-review/$orderId/'
      path: '/'
      fullPath: '/internal/order-review/$orderId/'
      preLoaderRoute: typeof PrivateInternalOrderReviewOrderIdIndexRouteImport
      parentRoute: typeof PrivateInternalOrderReviewOrderIdRoute
    }
    '/_private/internal/order-review/$orderId/layer/$layerId': {
      id: '/_private/internal/order-review/$orderId/layer/$layerId'
      path: '/layer/$layerId'
      fullPath: '/internal/order-review/$orderId/layer/$layerId'
      preLoaderRoute: typeof PrivateInternalOrderReviewOrderIdLayerLayerIdRouteImport
      parentRoute: typeof PrivateInternalOrderReviewOrderIdRoute
    }
  }
}

interface PrivateInternalMitraRegistrationRouteChildren {
  PrivateInternalMitraRegistrationRegistrationIdRoute: typeof PrivateInternalMitraRegistrationRegistrationIdRoute
  PrivateInternalMitraRegistrationIndexRoute: typeof PrivateInternalMitraRegistrationIndexRoute
}

const PrivateInternalMitraRegistrationRouteChildren: PrivateInternalMitraRegistrationRouteChildren =
  {
    PrivateInternalMitraRegistrationRegistrationIdRoute:
      PrivateInternalMitraRegistrationRegistrationIdRoute,
    PrivateInternalMitraRegistrationIndexRoute:
      PrivateInternalMitraRegistrationIndexRoute,
  }

const PrivateInternalMitraRegistrationRouteWithChildren =
  PrivateInternalMitraRegistrationRoute._addFileChildren(
    PrivateInternalMitraRegistrationRouteChildren,
  )

interface PrivateInternalOrderReviewOrderIdRouteChildren {
  PrivateInternalOrderReviewOrderIdIndexRoute: typeof PrivateInternalOrderReviewOrderIdIndexRoute
  PrivateInternalOrderReviewOrderIdLayerLayerIdRoute: typeof PrivateInternalOrderReviewOrderIdLayerLayerIdRoute
}

const PrivateInternalOrderReviewOrderIdRouteChildren: PrivateInternalOrderReviewOrderIdRouteChildren =
  {
    PrivateInternalOrderReviewOrderIdIndexRoute:
      PrivateInternalOrderReviewOrderIdIndexRoute,
    PrivateInternalOrderReviewOrderIdLayerLayerIdRoute:
      PrivateInternalOrderReviewOrderIdLayerLayerIdRoute,
  }

const PrivateInternalOrderReviewOrderIdRouteWithChildren =
  PrivateInternalOrderReviewOrderIdRoute._addFileChildren(
    PrivateInternalOrderReviewOrderIdRouteChildren,
  )

interface PrivateInternalOrderReviewRouteChildren {
  PrivateInternalOrderReviewOrderIdRoute: typeof PrivateInternalOrderReviewOrderIdRouteWithChildren
  PrivateInternalOrderReviewIndexRoute: typeof PrivateInternalOrderReviewIndexRoute
}

const PrivateInternalOrderReviewRouteChildren: PrivateInternalOrderReviewRouteChildren =
  {
    PrivateInternalOrderReviewOrderIdRoute:
      PrivateInternalOrderReviewOrderIdRouteWithChildren,
    PrivateInternalOrderReviewIndexRoute: PrivateInternalOrderReviewIndexRoute,
  }

const PrivateInternalOrderReviewRouteWithChildren =
  PrivateInternalOrderReviewRoute._addFileChildren(
    PrivateInternalOrderReviewRouteChildren,
  )

interface PrivateRouteRouteChildren {
  PrivateInternalDataManagementRoute: typeof PrivateInternalDataManagementRoute
  PrivateInternalHelpCenterRoute: typeof PrivateInternalHelpCenterRoute
  PrivateInternalHomeRoute: typeof PrivateInternalHomeRoute
  PrivateInternalMasterGeoserverRoute: typeof PrivateInternalMasterGeoserverRoute
  PrivateInternalMitraRegistrationRoute: typeof PrivateInternalMitraRegistrationRouteWithChildren
  PrivateInternalNotificationRoute: typeof PrivateInternalNotificationRoute
  PrivateInternalOrderReviewRoute: typeof PrivateInternalOrderReviewRouteWithChildren
  PrivateInternalOrderStatisticRoute: typeof PrivateInternalOrderStatisticRoute
  PrivateInternalUserManagementRoute: typeof PrivateInternalUserManagementRoute
  PrivateInternalWelcomeRoute: typeof PrivateInternalWelcomeRoute
  PrivateMitraCartRoute: typeof PrivateMitraCartRoute
  PrivateMitraDataRequestRoute: typeof PrivateMitraDataRequestRoute
  PrivateMitraHomeRoute: typeof PrivateMitraHomeRoute
  PrivateMitraMyDataRoute: typeof PrivateMitraMyDataRoute
  PrivateMitraNotificationRoute: typeof PrivateMitraNotificationRoute
  PrivateMitraTransactionHistoryRoute: typeof PrivateMitraTransactionHistoryRoute
  PrivateMitraWelcomeRoute: typeof PrivateMitraWelcomeRoute
  PrivateMitraBillingBillingCodeRoute: typeof PrivateMitraBillingBillingCodeRoute
  PrivateMitraHelpCenterTicketIdRoute: typeof PrivateMitraHelpCenterTicketIdRoute
  PrivateMitraHelpCenterIndexRoute: typeof PrivateMitraHelpCenterIndexRoute
}

const PrivateRouteRouteChildren: PrivateRouteRouteChildren = {
  PrivateInternalDataManagementRoute: PrivateInternalDataManagementRoute,
  PrivateInternalHelpCenterRoute: PrivateInternalHelpCenterRoute,
  PrivateInternalHomeRoute: PrivateInternalHomeRoute,
  PrivateInternalMasterGeoserverRoute: PrivateInternalMasterGeoserverRoute,
  PrivateInternalMitraRegistrationRoute:
    PrivateInternalMitraRegistrationRouteWithChildren,
  PrivateInternalNotificationRoute: PrivateInternalNotificationRoute,
  PrivateInternalOrderReviewRoute: PrivateInternalOrderReviewRouteWithChildren,
  PrivateInternalOrderStatisticRoute: PrivateInternalOrderStatisticRoute,
  PrivateInternalUserManagementRoute: PrivateInternalUserManagementRoute,
  PrivateInternalWelcomeRoute: PrivateInternalWelcomeRoute,
  PrivateMitraCartRoute: PrivateMitraCartRoute,
  PrivateMitraDataRequestRoute: PrivateMitraDataRequestRoute,
  PrivateMitraHomeRoute: PrivateMitraHomeRoute,
  PrivateMitraMyDataRoute: PrivateMitraMyDataRoute,
  PrivateMitraNotificationRoute: PrivateMitraNotificationRoute,
  PrivateMitraTransactionHistoryRoute: PrivateMitraTransactionHistoryRoute,
  PrivateMitraWelcomeRoute: PrivateMitraWelcomeRoute,
  PrivateMitraBillingBillingCodeRoute: PrivateMitraBillingBillingCodeRoute,
  PrivateMitraHelpCenterTicketIdRoute: PrivateMitraHelpCenterTicketIdRoute,
  PrivateMitraHelpCenterIndexRoute: PrivateMitraHelpCenterIndexRoute,
}

const PrivateRouteRouteWithChildren = PrivateRouteRoute._addFileChildren(
  PrivateRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PrivateRouteRoute: PrivateRouteRouteWithChildren,
  DemoRoute: DemoRoute,
  PublicAdminRoute: PublicAdminRoute,
  PublicRegisterRoute: PublicRegisterRoute,
  PublicRegistrationStatusRoute: PublicRegistrationStatusRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
